development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: couch_development
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: couch_test
  timeout: 5000
